### ISSUE TITLE
Upgrade rclone

### ISSUE THREAD

**Issue by djerfy** [zee-ahmed/kube-rclone#5]
Hi @zee-ahmed,

It's possible to have a more recent image with an rclone v1.52.x? (https://github.com/rclone/rclone/releases) 😃

Thanks

**Comment by simplyzee** [comment]
> Hi @zee-ahmed,
> 
> It's possible to have a more recent image with an rclone v1.52.x? (https://github.com/rclone/rclone/releases) 😃
> 
> Thanks

Hi @djerfy 

Yes, most definitely! I will have an update out soon. 

Cheers
Zee

**Comment by simplyzee** [comment]
@djerfy I've just merged a PR that upgrades rclone to v1.52.3 :+1:

**Comment by djerfy** [comment]
> 
> 
> @djerfy I've just merged a PR that upgrades rclone to v1.52.3 👍

Thanks a lot!
